services:
  ffc-ffd-auth:
    build:
      context: .
      target: production
    image: ffc-ffd-auth
    container_name: ffc-ffd-auth
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ffd-auth-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
