{{- include "ffc-helm-library.container-config-map" (list . "ffc-ffd-auth.config-map") -}}
{{- define "ffc-ffd-auth.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  GATEWAY_HOST: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
  DEFRA_ID_ENABLED: {{ quote .Values.auth.defraIdEnabled }}
  {{- if .Values.auth.defraIdEnabled }}
  DEFRA_ID_WELL_KNOWN_URL: {{ quote .Values.auth.defraIdWellKnownUrl }}
  DEFRA_ID_CLIENT_ID: {{ quote .Values.auth.defraIdClientId }}  
  DEFRA_ID_SERVICE_ID: {{ quote .Values.auth.defraIdServiceId }}
  DEFRA_ID_POLICY: {{ quote .Values.auth.defraIdPolicy }}  
  {{- if .Values.pr }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}{{ .Values.auth.defraIdRedirectPath }}
  {{ else }}
  DEFRA_ID_REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}{{ .Values.auth.defraIdRedirectPath }}
  {{- end }}
  {{- end }}
{{- end -}}
