{{- include "ffc-helm-library.container-secret" (list . "ffc-ffd-auth.container-secret") -}}
{{- define "ffc-ffd-auth.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  {{- if .Values.auth.defraIdClientSecret }}
  DEFRA_ID_CLIENT_SECRET: {{ quote .Values.auth.defraIdClientSecret }}
  {{- end }}
  {{- if .Values.auth.devAuthPrivateKey }}
  DEV_AUTH_PRIVATE_KEY: {{ quote .Values.auth.devAuthPrivateKey }}
  {{- end }}
  {{- if .Values.auth.devAuthPublicKey }}
  DEV_AUTH_PUBLIC_KEY: {{ quote .Values.auth.devAuthPublicKey }}
  {{- end }}
{{- end -}}
