{{- include "ffc-helm-library.azure-ingress" (list . "ffc-ffd-auth.ingress") -}}
{{- define "ffc-ffd-auth.ingress" -}}
{{- if not .Values.pr -}}
metadata:
  annotations:
    nginx.org/mergeable-ingress-type: minion
{{- else -}}
spec:
  rules:
  - host: {{ .Values.name }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.container.port }}
{{- end -}}
{{- end -}}
