environment: production
environmentCode:
name: ffc-ffd-auth
namespace: ffc-ffd
workstream: ffc-ffd
image: ffc-ffd-auth

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ffd-auth-config-map

containerSecret:
  name: ffc-ffd-auth-container-secret
  type: Opaque

deployment:
  priorityClassName: high

ingress:
  class: nginx
  endpoint: ffc-ffd
  server: example.com
  path: /auth

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3002

auth:
  defraIdEnabled: false
  defraIdWellKnownUrl: 
  defraIdClientId:
  defraIdClientSecret:
  defraIdServiceId:
  defraIdPolicy:
  defraIdRedirectPath: /auth/sign-in-oidc
  devAuthPrivateKey:
  devAuthPublicKey:

livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
